### ISSUE TITLE
Why only mutable borrows?

### ISSUE THREAD

**Issue by mlharaujo** [yvesdum/refbox#1]
Hi! I found this crate when trying to figure out how to implement trees without multiple ownership. This pattern of having a smart pointer with exclusive ownership together with the possibility of creating weak pointers that allow mutability was exactly what was needed!

I was just wondering why it's not possible to access data behind a Ref<_> without getting a mutable borrow? Why isn't there a borrow() method on Ref<T>?

Thanks!

**Comment by yvesdum** [comment]
Hi!

RefBox uses a single enum to track the state of the data. Mutable and immutable borrows are not tracked separately (like `Rc<RefCell<_>>` does), therefore it is not possible to have multiple borrows at the same time.

This is reflected in the API by only having borrow_mut(). A borrow() method could be added, but it is still not possible to have multiple immutable borrows at the same time. I thought having a borrow() method could possibly lead to confusion.

**Comment by mlharaujo** [comment]
Thanks! That makes sense.
